---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger
    app.kubernetes.io/component: service-agent
    app.kubernetes.io/instance: simplest
    app.kubernetes.io/name: simplest-agent
    app.kubernetes.io/part-of: jaeger
  name: simplest-agent
  namespace: observability
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: zk-compact-trft
    port: 5775
    protocol: UDP
    targetPort: 5775
  - name: http-config-rest
    port: 5778
    protocol: TCP
    targetPort: 5778
  - name: jg-compact-trft
    port: 6831
    protocol: UDP
    targetPort: 6831
  - name: jg-binary-trft
    port: 6832
    protocol: UDP
    targetPort: 6832
  - name: admin-http
    port: 14271
    protocol: TCP
    targetPort: 14271
  selector:
    app: jaeger
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/instance: simplest
    app.kubernetes.io/name: simplest
    app.kubernetes.io/part-of: jaeger
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger
    app.kubernetes.io/component: service-collector
    app.kubernetes.io/instance: simplest
    app.kubernetes.io/name: simplest-collector
    app.kubernetes.io/part-of: jaeger
  name: simplest-collector
  namespace: observability
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-zipkin
    port: 9411
    protocol: TCP
    targetPort: 9411
  - name: grpc-jaeger
    port: 14250
    protocol: TCP
    targetPort: 14250
  - name: http-c-tchan-trft
    port: 14267
    protocol: TCP
    targetPort: 14267
  - name: http-c-binary-trft
    port: 14268
    protocol: TCP
    targetPort: 14268
  - name: admin-http
    port: 14269
    protocol: TCP
    targetPort: 14269
  - name: grpc-otlp
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: http-otlp
    port: 4318
    protocol: TCP
    targetPort: 4318
  selector:
    app: jaeger
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/instance: simplest
    app.kubernetes.io/name: simplest
    app.kubernetes.io/part-of: jaeger
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "false"
  labels:
    app: jaeger
    app.kubernetes.io/component: service-collector
    app.kubernetes.io/instance: simplest
    app.kubernetes.io/name: simplest-collector
    app.kubernetes.io/part-of: jaeger
  name: simplest-collector-headless
  namespace: observability
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-zipkin
    port: 9411
    protocol: TCP
    targetPort: 9411
  - name: grpc-jaeger
    port: 14250
    protocol: TCP
    targetPort: 14250
  - name: http-c-tchan-trft
    port: 14267
    protocol: TCP
    targetPort: 14267
  - name: http-c-binary-trft
    port: 14268
    protocol: TCP
    targetPort: 14268
  - name: admin-http
    port: 14269
    protocol: TCP
    targetPort: 14269
  - name: grpc-otlp
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: http-otlp
    port: 4318
    protocol: TCP
    targetPort: 4318
  selector:
    app: jaeger
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/instance: simplest
    app.kubernetes.io/name: simplest
    app.kubernetes.io/part-of: jaeger
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger
    app.kubernetes.io/component: service-query
    app.kubernetes.io/instance: simplest
    app.kubernetes.io/name: simplest-query
    app.kubernetes.io/part-of: jaeger
  name: simplest-query
  namespace: observability
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-query
    port: 16686
    protocol: TCP
    targetPort: 16686
  - name: grpc-query
    port: 16685
    protocol: TCP
    targetPort: 16685
  - name: admin-http
    port: 16687
    protocol: TCP
    targetPort: 16687
  selector:
    app: jaeger
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/instance: simplest
    app.kubernetes.io/name: simplest
    app.kubernetes.io/part-of: jaeger
  sessionAffinity: None
  type: ClusterIP
