image:
  registry: ghcr.io
  repository: traefik/traefik-hub
  tag: "v3"
deployment:
  replicas: 2
ingressRoute:
  dashboard:
    enabled: false
ingressClass:
  enabled: false
providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true
    allowEmptyServices: true
logs:
  general:
    format: json
    level: DEBUG
  access:
    enabled: true
    format: json
    addInternals: false
    fields:
      general:
        defaultmode: keep
      headers:
        defaultmode: keep
metrics:
  addInternals: true
  prometheus: null
  otlp:
    enabled: true
    addentrypointslabels: true
    addrouterslabels: true
    addserviceslabels: true
    http:
      enabled: true
      endpoint: http://prometheus-stack-kube-prom-prometheus.observability.svc.cluster.local:9090/api/v1/otlp/v1/metrics
      tls:
        insecureSkipVerify: true
tracing:
  addInternals: true
  otlp:
    enabled: true
    http:
      enabled: true
      endpoint: http://simplest-collector.observability.svc.cluster.local:4318/v1/traces
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: "app.kubernetes.io/name"
                operator: In
                values:
                  - traefik
          topologyKey: kubernetes.io/hostname
        weight: 100
resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 256Mi
    cpu: 100m
ports:
  websecure:
    tls:
      enabled: true
      certResolver: le
additionalArguments:
  - '--certificatesresolvers.le.distributedAcme=true'
  - '--certificatesresolvers.le.distributedAcme.storage.kubernetes=true'
  - '--certificatesresolvers.le.distributedAcme.email=david.blaskow@traefik.io'
  - '--certificatesresolvers.le.distributedAcme.tlschallenge=true'
hub:
  token: hub-license
  apimanagement:
    enabled: true
    openApi:
      validateRequestMethodAndPath: false
  redis:
    endpoints: redis-master.redis.svc.cluster.local:6379
  experimental:
    aigateway: true